name: Test CI

on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Building App"
        run: |
          echo "Building App"

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:
      - name: "Deploy Dev"
        run: |
          echo "Deploying Dev"

  deploy-test:
    runs-on: 'ubuntu-latest'
    environment: 'test'
    needs: [build-and-publish, deploy-dev]
    steps:
      - name: "Deploy Test"
        run: |
          echo "Deploying Test"

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-dev, deploy-test]
    steps:
      - name: "Deploy Prod"
        run: |
          echo "Deploying Prod"
